import type { Route } from "./columns";
import type { TruckVisualization } from "./types";

// Placeholder data — backend `RouteResult` endpoint not wired here yet.
// See wiki/contracts/data-models.md and api-contract.md.
//
// `center_id` matches sampleCenters in src/components/centers/sample-data.ts.
export const sampleRoutes: Route[] = [
  {
    id: 1,
    center_id: 1,
    transport_id: "T-2401",
    route_code: "R-NORTE-1",
    driver_name: "Marta Ruiz",
    truck_type: "8pal",
    date: "2026-05-12",
    stops: 14,
    distance_km: 178.4,
    duration_min: 312,
  },
  {
    id: 2,
    center_id: 1,
    transport_id: "T-2402",
    route_code: "R-NORTE-2",
    driver_name: "Jordi Vila",
    truck_type: "6pal",
    date: "2026-05-12",
    stops: 9,
    distance_km: 112.7,
    duration_min: 218,
  },
  {
    id: 3,
    center_id: 2,
    transport_id: "T-2403",
    route_code: "R-LITORAL",
    driver_name: "Núria Soler",
    truck_type: "6pal",
    date: "2026-05-12",
    stops: 11,
    distance_km: 145.0,
    duration_min: 264,
  },
  {
    id: 4,
    center_id: 2,
    transport_id: "T-2404",
    route_code: "R-VALLES",
    driver_name: "Pere Mas",
    truck_type: "8pal",
    date: "2026-05-12",
    stops: 16,
    distance_km: 203.8,
    duration_min: 357,
  },
  {
    id: 5,
    center_id: 3,
    transport_id: "T-2405",
    route_code: "R-INTERIOR",
    driver_name: "Ana Pérez",
    truck_type: "van",
    date: "2026-05-12",
    stops: 7,
    distance_km: 88.2,
    duration_min: 174,
  },
];

// Mock TruckVisualization payload — must validate against the contract's shape.
export const sampleTruckVisualization: TruckVisualization = {
  truck_dims: { length_cm: 620, width_cm: 240, height_cm: 240 },
  pallet_dims: { length_cm: 120, width_cm: 80, height_cm: 15 },
  pallets: [
    {
      pallet_id: "PAL-001",
      label: "Stop 01",
      color: "#78e7ff",
      position: { x: 32, y: 24, z: 0 },
      dims: { length_cm: 120, width_cm: 80, height_cm: 88 },
      is_return: false,
      stop_ids: ["S-001"],
      products_summary: ["Beer bottle", "Water"],
    },
    {
      pallet_id: "PAL-002",
      label: "Stop 02",
      color: "#f7c948",
      position: { x: 166, y: 24, z: 0 },
      dims: { length_cm: 120, width_cm: 80, height_cm: 132 },
      is_return: false,
      stop_ids: ["S-002"],
      products_summary: ["Soft drink", "Coffee"],
    },
    {
      pallet_id: "PAL-003",
      label: "Stop 03",
      color: "#ff6b9a",
      position: { x: 300, y: 24, z: 0 },
      dims: { length_cm: 120, width_cm: 80, height_cm: 106 },
      is_return: false,
      stop_ids: ["S-003"],
      products_summary: ["Barrel", "Gas"],
    },
    {
      pallet_id: "PAL-004",
      label: "Return",
      color: "#9ef01a",
      position: { x: 434, y: 24, z: 0 },
      dims: { length_cm: 120, width_cm: 80, height_cm: 76 },
      is_return: true,
      stop_ids: ["S-004", "S-005"],
      products_summary: ["Returnables"],
    },
    {
      pallet_id: "PAL-005",
      label: "Stop 04",
      color: "#a78bfa",
      position: { x: 166, y: 136, z: 0 },
      dims: { length_cm: 120, width_cm: 80, height_cm: 118 },
      is_return: false,
      stop_ids: ["S-004"],
      products_summary: ["Wine", "Food"],
    },
    {
      pallet_id: "PAL-006",
      label: "Stop 05",
      color: "#ff9f1c",
      position: { x: 300, y: 136, z: 0 },
      dims: { length_cm: 120, width_cm: 80, height_cm: 96 },
      is_return: false,
      stop_ids: ["S-005"],
      products_summary: ["Dairy", "Disposable"],
    },
  ],
  route_geojson: null,
};
